# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 1024

# MD033/no-inline-html - Inline HTML
MD033: false

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD046/code-block-style: Code block style [Expected: fenced; Actual: indented]
MD046: false

#MD004/ul-style: Unordered list style [Expected: dash; Actual: asterisk]
MD004: false

#MD007/ul-indent: Unordered list indentation [Expected: 2; Actual: 4]
MD007: false