site_name: NAI LLM
site_url: https://naillm.howntnx.win
theme:
  name: material


# Site navigation

nav:
- Home: index.md
#- Possibilities: possibilities/possibilities.md
- Design:
  - Conceptual Design and Components: conceptual/conceptual.md
  - Sizing: sizing/sizing.md
- Infra Preparation:
  - infra/index.md
  - Workstation Setup: infra/workstation.md
  - Jumphost VM Tofu: infra/infra_jumphost_tofu.md
  # - Setup NKE Cluster: infra/infra_nke.md
  # - Setup NKP Cluster: infra/infra_nkp.md
- Tutorials:
  - Nutanix Enterprise AI in NKP Workspace (NAI):
    - Getting Started: nai/index.md
    - Setup NKP Cluster: nai/infra_nkp_nai.md
    - Pre-requisites NAI: nai/pre_reqs_nai.md
    - Deploy NAI: nai/deploy_nai.md
    - Test NAI: nai/test_nai.md
  - Nutanix Enterprise AI v2.0 (NAI):
    - Getting Started: iep/index.md
    - Setup NKP Cluster: infra/infra_nkp.md
    - Pre-requisites NAI: iep/iep_pre_reqs.md
    - Deploy NAI: iep/iep_deploy.md
    - Test NAI: iep/iep_test.md
  - Air-gapped Nutanix Enterprise AI v2.0 (NAI):
    - Getting Started: airgap_nai/index.md
    - Harbor Container Registry: airgap_nai/harbor.md
    - Setup Air-gapped NKP Cluster: airgap_nai/infra_nkp_airgap.md
    - Pre-requisites NAI: airgap_nai/airgap_nai_pre_reqs.md
    - Deploy NAI: airgap_nai/airgap_nai_deploy.md
    - Test NAI: airgap_nai/airgap_nai_test.md
  - GPT-in-a-Box v1 NVD Reference App:
    - Getting Started: llmmgmt/index.md
    - Setup NKE Cluster: infra/infra_nke.md
    - Pre-requisites: llmmgmt/llm_pre_reqs.md
    - Deploy Management Cluster: llmmgmt/llm_mgt_deploy.md
    - Deploy Dev Cluster: llmmgmt/llm_dev_deploy.md
    - Test LLM App: llmmgmt/llm_test.md
- Appendix:
  - Jumphost VM Manual: infra/infra_jumphost.md
  - NKP The Hard Way: appendix/infra_nkp_hard_way.md
  - Harbor Container Registry: infra/harbor.md
  - Deploying Private CA Certificate to NKP Cluster: appendix/nkp_cert_ds.md
  - Opentofu: appendix/opentofu.md
- References:
  - Nutanix Components: ntxcomponents/ntxcomponents.md
  - Tools used and why?: tools/tools.md
  - Contributing: contributing.md
  - Roadmap: roadmap.md
- Simulators:
  - static/index.md
  - Pods and Nodepools Simulation: static/scheduling-mixed-pods-and-nodepool-v1.html
  - K8S Deployment Strategies: static/k8s-deployment-strategies-visualizer.html
- Takeaways: takeaways/takeaways.md


# Repository

repo_name: nutanix-japan/nai-llm
repo_url: https://github.com/nutanix-japan/nai-llm
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2016 - 2025 Nutanix

# Configuration

theme:
  palette:
  #   - primary: deep purple
  #   - accent: black

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.path
  - navigation.footer
  - navigation.tracking
  # - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  # - navigation.expand
  - navigation.top
  - navigation.integrateåß
  - search.highlight
  - search.suggest
  - search.share
  - toc.follow
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.code.annotate
  #- content.tabs.link

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true
- attr_list
- md_in_html
- pymdownx.keys
- markdown_grid_tables

plugins:
- termynal:
    prompt_literal_start:
    - "$"
    - ">"
    - ">>>"
- search
#- git-authors
- git-revision-date-localized:
    enable_creation_date: true
    enabled: !ENV [CI, false]
# - git-committers:
#     repository: nutanix-japan/nai-llm
#     branch: main
#     enabled: !ENV [CI, false]

# # Style sheeting here
# extra_css:
#   - stylesheets/extra.css

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/nutanix-japan
  - icon: fontawesome/brands/github
    link: https://github.com/jesse-gonzalez

